import AppLayout from "@/components/layout/AppLayout";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-satoshi"
      >
        <SidebarProvider>
          <AppLayout>
            {children}
          </AppLayout>
        </SidebarProvider>
      </body>
    </html>
  );
}
